### PR TITLE
#11 Created a React Site to replace old public site

### PR DESCRIPTION
**Pull request by coreyjjames**
# This is a pull request responding to issue  #11 .

This pull request contains a new react site to replace the current public site. The react site is in a working state, but their is still some work to be done.

It is complete enough that other people can now join to finish it.
And, I would like to also continue working on this.

Let me know your thoughts in the comments. 

Thanks @joshghent  for the opportunity to work on this project.

# Important Notes
I had to restructure the repository in order to keep the original version of the site and add the react app. 
The original could eventually be removed once we have the react app fine tuned.
I added the following directories to make this happen.
- nodeChatOriginal - this contains all files that were in the project before any changes. 
- nodeChatReact - this contains the new react app.
- nodeChatServer - this is a copy of the server separated from nodeChatOriginal.

# Running React App
cd into nodeChatServer and run the command "node index.js" in your command prompt. 

cd into nodeChatReact and run the command "npm start" in your command prompt.

# More Info
I will be posting a blog post about this Pull Request on my website within the week. I will go more in-depth over there.
[My Blog](https://coreyjames.me/)

### CODE REVIEW

**Comment by coreyjjames** [comment]
@dbrudner

**Comment by joshghent** [comment]
@coreyjjames This is absolutely awesome! 🎉 Maybe we should split out the server into a separate repo? So we can deploy it independently? What do you think? If you would like to take over maintaining this, I will create a new organisation and add you to it, there we can expand it. What do you think? The Nodechat name is taken, but perhaps we can come up with something else. My original vision for this project was to have off the record chat that disappeared after you used it so we can relate the name for that

Nice job on the blog too! That's great, I think it's good to blog as you develop, it helps you clarify your own understanding.

**Comment by coreyjjames** [comment]
Thanks @joshghent! Ya I definitely agree that splitting the server and client into different repo's would be a great idea. It would make the development process allot cleaner.  

Sure, I can be a maintainer for this. 

Since were working with react, we could target people integrating this app as a component into there exsisting app. And, The name could relate to that aswell. 

Here's a few ideas for a name.
 - OffRecordChat
 - ChatComponent
 - LoglessChat
 - PrivateChat (probably want to inplement some  encription if we chose this name)
 - ReactChat
 - ReactNodeChat

**Comment by joshghent** [comment]
Ok I've created https://github.com/OTRChat and invited you @coreyjjames - let's get these conflicts fixed, merged in and then I can move the entire repo to the organisation. There we can split out the server

**Comment by coreyjjames** [comment]
@joshghent I accepted the invitation and Conflicts should be all fixed now.

**Pull request merged**
